# Site settings
title: All things coder.
email: aram.malinich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for ideas, inspection, and collaboration of all things software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://amalinich.github.io" # the base hostname & protocol for your site
twitter_username: topramnik
github_username:  amalinich

# Build settings
markdown: kramdown
